spring:
  application:
    name: discodeit
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: false
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      continue-on-error: false
      encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
    datasource:
      url: ${spring.datasource.url:}
      driver-class-name: ${spring.datasource.driver-class-name:}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto:}
    storage:
      type: ${discodeit.storage.type:}
      path: ${discodeit.storage.local.root-path:}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size:}
      max-request-size: ${spring.servlet.multipart.max-request-size:}
logging:
  level:
    root: INFO
    org.springframework.jdbc.datasource.init: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

discodeit:
  storage:
    type: local
    local:
      root-path: storage/binary-content
